kassandra/inquisitor/urls.py
from django.urls import path

from . import views

app_name = "inquisitor"

urlpatterns = [
    path("", views.index, name="index"),
    path("documents", views.text_documents, name="text_documents"),
    path("predictions/<int:text_document_id>", views.predictions, name="predictions"),
    path(
        "predictions/store/<int:text_document_id>",
        views.store_predictions,
        name="store_predictions",
    ),
    path(
        "predictions/expected/<int:text_document_id>",
        views.expected_prediction,
        name="expected_prediction",
    ),
]

kassandra/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),  # noqa: DJ05
    path("", include("kassandra.inquisitor.urls")),  # noqa: DJ05
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kassandra/inquisitor/models.py
from django.db import models


class PredictedUseCase(models.Model):
    class Meta:
        pass

    name = models.CharField(max_length=255, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class TextDocument(models.Model):
    class Meta:
        get_latest_by = "pk"

    text = models.TextField()
    predicted_use_case = models.ForeignKey(
        PredictedUseCase, on_delete=models.PROTECT, null=True, blank=True
    )
    accurate_use_case = models.BooleanField(null=True)
    expected_use_case = models.CharField(max_length=100, blank=True, default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

kassandra/inquisitor/forms.py
from django import forms

from .models import TextDocument


class TextDocumentForm(forms.ModelForm):
    class Meta:
        model = TextDocument
        fields = ("text",)
        labels = {
            "text": "Review Text",
        }
        widgets = {
            "text": forms.Textarea(attrs={"cols": 120, "rows": 15}),
        }
        help_texts = {
            "text": "Please enter a review",
        }


class ExpectedPredictionForm(forms.ModelForm):
    class Meta:
        model = TextDocument
        fields = (
            "text",
            "expected_use_case",
        )
        labels = {
            "text": "Review Text",
            "expected_use_case": "Expected Prediction",
        }
        widgets = {
            "text": forms.Textarea(
                attrs={
                    "cols": 120,
                    "rows": 15,
                    "class": "disabled",
                    "readonly": "readonly",
                }
            ),
        }
        help_texts = {
            "expected_use_case": "Please enter the expected prediction",
        }

    def clean(self):
        """ Validate form data
        """
        cleaned_data = super().clean()

        if cleaned_data["expected_use_case"] == "":
            self.add_error("expected_use_case", "Please provide an expected prediction")

        return cleaned_data

kassandra/inquisitor/views.py
import json
import logging
import string
from os import environ as os_environ, path as os_path

from django.contrib import messages
from django.db import transaction
from django.http import HttpResponseBadRequest, HttpResponseServerError
from django.shortcuts import get_object_or_404, redirect, render, reverse

from django_tables2 import RequestConfig
from review_analyzer import Review
from sklearn.preprocessing import MultiLabelBinarizer

from .classifiers import CustomModelPrediction
from .forms import ExpectedPredictionForm, TextDocumentForm
from .models import PredictedUseCase, TextDocument
from .tables import PredictionsTable, TextDocumentTable

LOGGER = logging.getLogger(__name__)

NO_PREDICTIONS_ERROR_MESSAGE = "Unable to produce predictions. Please try again"


def index(request):
    """ Index
    """
    if request.method == "POST":
        form = TextDocumentForm(request.POST)

        if form.is_valid():
            with transaction.atomic():
                text_document = form.save()

                messages.success(request, "Thank you for your submission")
                return redirect(
                    reverse("inquisitor:predictions", args=(text_document.id,))
                )
    else:
        form = TextDocumentForm()

    return render(request, "index.html", {"text_document_form": form})


def text_documents(request):
    """ Retrieve text documents
    """
    queryset = TextDocument.objects.select_related("predicted_use_case")

    table = TextDocumentTable(queryset)
    RequestConfig(request, paginate={"per_page": 10}).configure(table)

    return render(request, "text_documents.html", {"table": table})


def predictions(request, text_document_id):
    """ Analyse text documents and predict use cases
    """
    document = {}
    table = None

    expected_files = [
        "KERAS_MODEL_FILE",
        "MULTI_HOT_ENCODE_MODEL_FILE",
        "TAGS_LIST_FILE",
    ]
    missing_file = False

    for expected_file in expected_files:
        if expected_file not in os_environ:
            LOGGER.error("%s not set", expected_file)
            missing_file = True

    if missing_file:
        messages.error(request, NO_PREDICTIONS_ERROR_MESSAGE)
    else:
        text_document = get_object_or_404(TextDocument, pk=int(text_document_id))

        multi_hot_encode_model_file = os_environ["MULTI_HOT_ENCODE_MODEL_FILE"]
        keras_model_file = os_environ["KERAS_MODEL_FILE"]
        tags_list_file = os_environ["TAGS_LIST_FILE"]

        # check if files exist
        if not all(
            [
                os_path.exists(multi_hot_encode_model_file),
                os_path.exists(keras_model_file),
                os_path.exists(tags_list_file),
            ]
        ):
            LOGGER.error("Model files and tags list file must be provided")
            return HttpResponseServerError(
                "Unexpected error. Please contact system administrator"
            )

        tag_encoder = multi_hot_encode_tags(tags_list_file)
        features = nlp_analysis(text_document.text)
        classifier = CustomModelPrediction.from_path(
            multi_hot_encode_model_file, keras_model_file
        )
        predictions = classifier.predict([features])

        document["text_document"] = text_document
        document["features"] = features
        document["predicted_use_case"] = predict_use_case(predictions, tag_encoder)

        table = PredictionsTable([document])
        RequestConfig(request, paginate={"per_page": 10}).configure(table)

    return render(request, "predictions.html", {"table": table})


def multi_hot_encode_tags(tags_list_file):
    """ Extract tags list from file.
    Multi hot encode tags list
    """
    with open(tags_list_file, "r") as fhandle:
        tags_list = json.load(fhandle)["tags_list"]

    # multi hot encode tags list
    tag_encoder = MultiLabelBinarizer()
    tag_encoder.fit_transform(tags_list)

    return tag_encoder


def nlp_analysis(text):
    """ Perform natural language processing (NLP) on text
    """
    # remove punctuation from text
    review_text = text.translate(str.maketrans("", "", string.punctuation))
    # perform NLP on review text
    review = Review(review_text, preprocess=True)
    # lemmatize features
    features = " ".join(review.lemmatize(review.features))

    return features


def predict_use_case(predictions, tag_encoder):
    """ Predict use case
    """
    predicted_use_case = "unknown"

    for i in range(len(predictions)):
        for idx, val in enumerate(predictions[i]):
            if val > 0.6:
                predicted_use_case = tag_encoder.classes_[idx]
                break

    return predicted_use_case


def store_predictions(request, text_document_id):
    """ Store predictions if user determines them
    to be accurate
    """
    missing_key = False
    for key in ["use_case", "accurate"]:
        if key not in request.GET:
            LOGGER.error("%s not present", key)
            missing_key = True

    if missing_key:
        return HttpResponseBadRequest("Error: Missing data")

    accurate = True if request.GET["accurate"] == "true" else False

    text_document = get_object_or_404(TextDocument, pk=int(text_document_id))
    predicted_use_case, _ = PredictedUseCase.objects.get_or_create(
        name=request.GET["use_case"]
    )
    text_document.predicted_use_case = predicted_use_case
    text_document.accurate_use_case = accurate
    text_document.save()

    return redirect(reverse("inquisitor:text_documents"))


def expected_prediction(request, text_document_id):
    """ Store expected use case if predicted use case
    is inaccurate
    """
    text_document = get_object_or_404(TextDocument, pk=int(text_document_id))

    if request.method == "POST":
        form = ExpectedPredictionForm(request.POST, instance=text_document)

        if form.is_valid():
            with transaction.atomic():
                text_document = form.save()

                messages.success(request, "Thank you for your submission")
                return redirect(reverse("inquisitor:text_documents"))
    else:
        form = ExpectedPredictionForm(instance=text_document)

    return render(
        request,
        "expected_prediction.html",
        {"expected_prediction_form": form, "text_document": text_document},
    )

kassandra/inquisitor/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <!-- Logo -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">
                        {{instance_name}}

                      {% if debug %}
                        {% if environment == "docker"%}
                          <span class="badge badge-primary">
                        {% elif environment == "local"%}
                          <span class="badge badge-success">
                        {% endif %}

                        {{ environment }}
                        </span>
                      {% endif %}
                    </a>

                    <button
                        class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbar-main">
                        <span class="navbar-toggler-icon"></span>
                        <span class="navbar-toggler-icon"></span>
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <!-- Nav Bar Links -->
                <div id="navbar-main" class="collapse navbar-collapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'inquisitor:index' %}">
                                New Text Entry
                            </a>
                        </li>
                        <li>
                            <a class="nav-link" href="{% url 'inquisitor:text_documents' %}">
                                Text Documents
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <p>
                {% if messages %}
                    {% for message in messages %}
                        {% if message.tags %}
                            {% if message.tags == 'error' %}
                                <div class="alert alert-danger" role="alert">
                                    {{ message }}
                                </div>
                            {% else %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    {{ message }}
                                </div>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </p>

            {% block content %}{% endblock %}
        </div>
        <!-- JavaScript Boostrap libraries -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

kassandra/inquisitor/templates/bootstrap_form.html
{% load i18n widget_tweaks %}
{% comment %}See http://stackoverflow.com/a/27239186/1983841{% endcomment %}
{% for field in form %}
{% if field.errors %}
<div class="form-group form-group-sm has-danger">
    {% if field not in form.hidden_fields %}
    <strong>
	<label class="col-sm-6 form-control-label" for="id_{{ field.name }}">
	    {{ field.label }}
	</label>
    </strong>

    {% if "Upload" in field.label or field.label == "Parking" or field.label == "Outside Spaces" or field.label == "Features" or field.label == "Rooms" or field.label == "Heating" %}
    {{ field }}
    <div class="col-sm-10">
	<span class="help-block">
	    {% for error in field.errors %}
	    <font color="red">{{ error }}</font>
	    {% endfor %}
	</span>
    </div>
    {% else %}
    <div class="col-md-10">
	{{ field|attr:"class:form-control" }}
	<span class="help-block">
	    {% for error in field.errors %}
	    <font color="red">{{ error }}</font>
	    {% endfor %}
	</span>
    </div>
    {% endif %}
    {% else %}
    {{ field }}
    {% endif %}
</div>
{% else %}
<div class="form-group form-group-sm">
    {% if field not in form.hidden_fields %}
    <strong>
	<label class="col-sm-6 form-control-label" for="id_{{ field.name }}">
	    {{ field.label }}
	</label>
    </strong>

    {% if "Upload" in field.label or field.label == "Parking" or field.label == "Outside Spaces" or field.label == "Features" or field.label == "Rooms" or field.label == "Heating" %}
    {{ field }}
    {% else %}
    <div class="col-sm-10">
	{{ field|attr:"class:form-control" }}
	{% if field.help_text %}
	<p class="help-block"><small>{{ field.help_text }}</small></p>
	{% endif %}
    </div>
    {% endif %}
    {% else %}
    {{ field }}
    {% endif %}
</div>
{% endif %}
{% endfor %}

kassandra/inquisitor/templates/expected_prediction.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Expected Prediction{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-2"></div>

    <div class="col-md-8">
        <p>
            <h5>
                Provide the expected prediction for this text
            </h5>
        </p>
        <p>
            <form action="{% url 'inquisitor:expected_prediction' text_document.id %}" method="POST">
                {% csrf_token %}
                {% with expected_prediction_form as form %}
                {% include "bootstrap_form.html" %}
                {% endwith %}

                <div class="form-group form-group-sm">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input
                            type="submit"
                            class="btn btn-primary" value="Submit" />
                    </div>
                </div>
            </form>
        </p>
    </div>
</div>
{% endblock %}

kassandra/inquisitor/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Kassandra
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>

        <div class="col-md-8">
            <p>
                <h4>
                    In greek mythology, Kassandra was a woman who uttered accurate
                    prophecies, but was never believed.
                </h4>
            </p>
            <p>
                <h5>
                    This online platform that analyses product
                    reviews to accurately predict use cases.
                    Let see if you believe the predictions
                </h5>
            </p>
            <p>
                <form action="{% url 'inquisitor:index' %}" method="POST">
                    {% csrf_token %}
                    {% with text_document_form as form %}
                        {% include "bootstrap_form.html" %}
                    {% endwith %}

                    <div class="form-group form-group-sm">
                        <div class="col-sm-offset-2 col-sm-10">
                            <input
                                type="submit"
                                class="btn btn-primary" value="Submit" />
                        </div>
                    </div>
                </form>
            </p>
        </div>
    </div>
{% endblock %}

kassandra/inquisitor/templates/prediction_accuracy.html
<a class="btn btn-primary" role="button"
   data-toggle="modal"
   data-target="#myModal_{{ record.text_document.id }}">
    Decide
</a>

<!-- Make Decision Modal -->
<div class="modal fade" id="myModal_{{ record.text_document.id }}"
     tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document"
         id="{{ record.text_document.id }}">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">
                    Prediction Accuracy
                </h4>
                <button type="button" class="close"
                        data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Is the predicted use case accurate?
            </div>
            <div class="modal-footer">
                <a
                    href="{% url 'inquisitor:store_predictions' record.text_document.id %}?use_case={{ record.predicted_use_case }}&accurate=true"
                    role="button" class="btn btn-success">
                    Accurate
                </a>
                <a href="{% url 'inquisitor:store_predictions' record.text_document.id %}?use_case={{ record.predicted_use_case }}&accurate=false" role="button" class="btn btn-danger">
                    Inaccurate
                </a>
                <a role="button" class="btn btn-light" data-dismiss="modal">
                    Cancel
                </a>
            </div>
        </div>
    </div>
</div>

kassandra/inquisitor/templates/predictions.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load render_table from django_tables2 %}

{% block title %}
    Predictions
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-1"></div>

        <div class="col-md-10">
            {% if table.rows|length > 0 %}
                {% render_table table %}
            {% else %}
                <h3>No predictions available at this time</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

kassandra/inquisitor/templates/text_documents.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load render_table from django_tables2 %}

{% block title %}Text Documents{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-1"></div>

    <div class="col-md-10">
        {% if table.rows|length > 0 %}
        {% render_table table %}
        {% else %}
        <h3>No text documents available at this time</h3>
        {% endif %}
    </div>
</div>
{% endblock %}